addSbtPlugin("com.thesamet"  % "sbt-protoc"     % "1.0.6")
addSbtPlugin("org.typelevel" % "sbt-fs2-grpc"   % "2.5.4")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"   % "0.10.4")
addSbtPlugin("c.github.sbt"  % "sbt-ci-release" % "1.5.11")
