name: CI

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
            jobtype: 1

    runs-on: ${{ matrix.os }}
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: olafurpg/setup-scala@v13
      with:
        java-version: "openjdk@1.${{ matrix.java }}.0"

    - uses: coursier/cache-action@v6

    - name: Build and test
      run: |
        case ${{ matrix.jobtype }} in
          1)
            sbt -v "scalafmtCheckAll; +test;"
            ;;
          *)
            echo unknown jobtype
            exit 1
        esac        
      shell: bash
