name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
            jobtype: 1

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: olafurpg/setup-scala@v13
      with:
        java-version: "openjdk@1.${{ matrix.java }}.0"

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: olafurpg/setup-scala@v12
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v6
    - uses: olafurpg/setup-gpg@v3
    - run: sbt -v ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    - name: clean up
      run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
