name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
            jobtype: 1

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: olafurpg/setup-scala@v13
      with:
        java-version: "openjdk@1.${{ matrix.java }}.0"

    - uses: coursier/cache-action@v6

    - name: Build and test
      run: |
        case ${{ matrix.jobtype }} in
          1)
            sbt -v "scalafmtCheckAll; +test;"
            ;;
          *)
            echo unknown jobtype
            exit 1
        esac        
      shell: bash

  release:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup
      uses: olafurpg/setup-scala@v13
      with:
        java-version: "openjdk@1.17.0"

    - uses: coursier/cache-action@v6

    - uses: olafurpg/setup-gpg@v3

    - name: Release
      run: sbt -v ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
