name: Snapshot

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  snapshot:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
        fetch-depth: 0

    - name: Setup
      uses: olafurpg/setup-scala@v13
      with:
        java-version: "openjdk@1.17.0"

    - uses: coursier/cache-action@v6

    - uses: olafurpg/setup-gpg@v3

    - name: Snapshot Release
      run: sbt -v ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
